#!/usr/bin/env python3
"""Generate the human-readable launcher index from games.json."""
from __future__ import annotations

import argparse
import json
import pathlib
import sys


# A column can be served by more than one store key: a Battle.net game version
# launches by uid rather than by product code, but it is still a Battle.net
# launcher sitting in BattleNet/.
STORE_COLUMNS = (
    (("steam",), "Steam", "Steam"),
    (("epic",), "Epic", "Epic"),
    (("battlenet", "battlenetuid"), "Battle.net", "BattleNet"),
    (("ubisoft",), "Ubisoft", "Ubisoft"),
)


def markdown_text(value: str) -> str:
    return value.replace("|", "\\|").replace("\r", " ").replace("\n", " ")


def render(games: list[dict]) -> str:
    launcher_count = sum(len(game["stores"]) for game in games)
    lines = [
        "# Game index",
        "",
        "<!-- Generated by scripts/index.py from games.json. Do not edit by hand. -->",
        "",
        f"{len(games)} games and {launcher_count} store-specific launchers.",
        "",
        "| Game | Steam | Epic | Battle.net | Ubisoft |",
        "|---|:---:|:---:|:---:|:---:|",
    ]
    for game in sorted(games, key=lambda item: item["name"].lower()):
        cells = []
        for keys, label, directory in STORE_COLUMNS:
            if any(key in game["stores"] for key in keys):
                cells.append(f"[{label}]({directory}/{game['out']})")
            else:
                cells.append("—")
        lines.append(f"| {markdown_text(game['name'])} | {' | '.join(cells)} |")
    lines.extend(
        [
            "",
            "Store availability and links are generated directly from "
            "[`games.json`](games.json).",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--manifest", default="games.json")
    parser.add_argument("--output", default="GAMES.md")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    manifest = pathlib.Path(args.manifest)
    output = pathlib.Path(args.output)
    games = json.loads(manifest.read_text(encoding="utf-8"))
    expected = render(games)

    if args.check:
        actual = output.read_text(encoding="utf-8") if output.exists() else ""
        if actual != expected:
            print(f"{output} is stale; run: python scripts/index.py", file=sys.stderr)
            return 1
        return 0

    if not output.exists() or output.read_text(encoding="utf-8") != expected:
        output.write_text(expected, encoding="utf-8", newline="\n")
        print(f"wrote {output} ({len(games)} games)")
    else:
        print(f"{output} is already current")
    return 0


if __name__ == "__main__":
    sys.exit(main())
